spring.application.name=StorageStructure
spring.datasource.url =jdbc:postgresql://localhost:5432/storage_DB
spring.datasource.username=postgres
spring.datasource.password=admin@123
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081


